services:
  - type: web
    name: fynda-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn fynda.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DJANGO_SETTINGS_MODULE
        value: fynda.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fynda-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com,.fynda.shop"

databases:
  - name: fynda-db
    plan: free
